### ISSUE TITLE
Wooden water bucket quest

### ISSUE THREAD

**Issue by Sedus** [benbenlaw/caveopolis#2]
1. Crafted basic barrel
2. Crafted empty wooden bucket
3. Wooden water bucket quest automatically got completed

Version: A1.2

**Comment by Sedus** [comment]
Same with basic barrel and eroder

**Comment by Sedus** [comment]
Same with basic barrel and eroder

**Comment by MickeyMouseYT** [comment]
> Same with basic barrel and eroder

This problem has been fixed, update your modpack! To update a modpack in CurseForge right click, select Versions, choose version from drop down menu and hit continue.
Don't forget to backup your world..

"Caveopolis (A2.0)

Quests for machines now actually require you to have that machines
Quests for lava and water buckets now actually require you to have that bucket
Ingot to dust eroder recipe now uses 2 ingots to make 1 dust instead of a chance
Slightly adjust enderium right click usage on dragon egg to make the block check happen first may fix issues where the egg doesn't drop as a item
Server files now show caveopolis MOTD
Spawning system now follows the rules, may not be perfect but should be a lot better now
Osmium and fluorite now work in the fragment combiner
Creepers no longer spawn
Dirt can now be made in the organic producer
Added a bunch of QOL mods"
