### ISSUE TITLE
Auto complete Issue?

### ISSUE THREAD

**Issue by Kkuramax** [benbenlaw/caveopolis#6]
The 3 machines auto completed once I made the Advanced barrel

![Cave](https://user-images.githubusercontent.com/110275672/181876992-e0d2a169-c68c-4a12-9322-e9f8188281cc.PNG)
.

**Comment by MickeyMouseYT** [comment]
> The 3 machines auto completed once I made the Advanced barrel
> 
> ![Cave](https://user-images.githubusercontent.com/110275672/181876992-e0d2a169-c68c-4a12-9322-e9f8188281cc.PNG) .

This problem has been fixed, update your modpack! To update a modpack in CurseForge right click, select Versions, choose version from drop down menu and hit continue.
Don't forget to backup your world..

"Caveopolis (A2.0)

Quests for machines now actually require you to have that machines
Quests for lava and water buckets now actually require you to have that bucket
Ingot to dust eroder recipe now uses 2 ingots to make 1 dust instead of a chance
Slightly adjust enderium right click usage on dragon egg to make the block check happen first may fix issues where the egg doesn't drop as a item
Server files now show caveopolis MOTD
Spawning system now follows the rules, may not be perfect but should be a lot better now
Osmium and fluorite now work in the fragment combiner
Creepers no longer spawn
Dirt can now be made in the organic producer
Added a bunch of QOL mods"
